name: booking-order-app # change this to your app name
services:
  order-service: # change this to your service name
    container_name: order-service # change this to your service name
    image: marcellinusaditya/order-service:1 # change this to your image name
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    ports:
      - "8004:8004" # change this to your port
    env_file:
      - .env
